##
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://containers-us-west-41.railway.app:6596/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:6XAJ1beLIGcMipQM44nX}
    driver-class-name: org.postgresql.Driver
##
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: hXDdkbLC
  expiration: 86400000
server:
  port: 8083

