##
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://containers-us-west-117.railway.app:5807/railway}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:jqanKALEAVN3NdPw9yh1}
    driver-class-name: org.postgresql.Driver
##
  mail:
    host: smtp.gmail.com
    port: 587
    username: sonich.edu@gmail.com
    password: umnrvgjzzsfohitg
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 2A472D4B6150645367556B58703273357638792F423F4528482B4D6251655468
  expiration: 86400000
server:
  port: 8083

